name: build

on:
  push:
    branches-ignore:
      - 0.9.3
      - 0.9.4
      - 0.9.5
      - 0.9.6
      - 0.9.7
      - 0.9.8
      - 0.10.0
      - 0.10.1
      - 0.10.2
      - 0.11.0
      - weblate**

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build project with Maven
        run: mvn -T 4 --batch-mode -Djava.awt.headless=true verify -P enableTests,enableCheckStyle
