name: "Build & Test"
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 6 * * 1' # Run every monday at 06:00 UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        node: ['16']
        include:
          - os: ubuntu
            node: '17'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: mvn clean install
      - run: mvn nbm:cluster-app nbm:run-platform
        working-directory: modules/application
